services:
  - type: web
    name: karigari-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://karigari-ruddy.vercel.app

  - type: web
    name: karigari-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://karigari-2xcq.onrender.com
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://karigari-2xcq.onrender.com/api/$1
      - type: rewrite
        source: /(.*)
        destination: /index.html